src/OTP/ExtranetApp/Controllers/HomeOwnerController.cs
using BusinessLogic.Enums;
using ExtranetApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DataAccess;
using DataAccess.Enums;
using System.Threading;
using BusinessLogic.ServiceContracts;
using ExtranetApp.Resources.Controllers;
using Common;
using Common.Converters;
using BusinessLogic.Objects.Templates.Email;
using ExtranetApp.Models.HomeOwner;
using BusinessLogic.Objects.Session;
using Common.Extensions;
using Common.Exceptions;
using BusinessLogic.Objects;
using ExtranetApp.Helpers;
using ExtranetApp.Security;
using DataAccess.CustomObjects;
using System.IO;

namespace ExtranetApp.Controllers
{
    public class HomeOwnerController : BaseController
    {
        #region Ctor

        public HomeOwnerController(IStateService stateService,
            IMessageService messageService,
            IDictionaryCountryService dictionaryCountryService,
            IDictionaryCultureService dictionaryCultureService,
            IRolesService roleService,
            IUserService userService,
            IScheduledVisitsService scheduledVisitsService,
            IReservationsService reservationService,
            IPropertiesService propertiesService,
            IConfigurationService configurationService,
            IUnitsService unitService,
            ISettingsService settingsService,
            IAuthorizationService authorizationService,
            IBlobService blobService)
            : base(new Dictionary<Type, object>() {{ 
                typeof(IStateService), stateService }, {
                typeof(IMessageService), messageService }, {
                typeof(IDictionaryCountryService), dictionaryCountryService }, {                                                                    
                typeof(IDictionaryCultureService), dictionaryCultureService},{
                typeof(IRolesService), roleService }, {
                typeof(IUserService), userService }, 
                { typeof(IScheduledVisitsService), scheduledVisitsService},
                { typeof(IReservationsService), reservationService},
                { typeof(IPropertiesService), propertiesService },
                { typeof(IConfigurationService), configurationService},
                { typeof(IUnitsService), unitService},
                { typeof(ISettingsService), settingsService},
                { typeof(IAuthorizationService), authorizationService},
                { typeof(IBlobService), blobService},
            }
            )
        {
        }

        #endregion

        /// <summary>
        /// Just for backward compability (redirects to new action)
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return RedirectToAction("AboutJoin");
        }

        /// <summary>
        /// Streams OwnerAgreement pdf to the browser
        /// </summary>
        /// <returns></returns>
        public ActionResult OwnerAgreement()
        {
            return File(BlobService.DownloadFileByUrl("FullFormOwnerContract.pdf", "pdfs"), "application/pdf");
        }

        /// <summary>
        /// Streams ShortTermRentalAgreement pdf to the browser
        /// </summary>
        /// <returns></returns>
        public ActionResult ShortTermRentalAgreement()
        {
            return File(BlobService.DownloadFileByUrl("FullFormOwnerGuestContract.pdf", "pdfs"), "application/pdf");
        }

        /// <summary>
        /// Opens About Join view
        /// </summary>
        /// <param name="id">Affility Signup Code</param>
        /// <returns></returns>
        public ActionResult AboutJoin(string id = "")
        {
            this.StateService.RemoveFromSession(SessionKeys.HomeownerSignUpCode.ToString());
            this.StateService.AddToSession(SessionKeys.HomeownerSignUpCode.ToString(), id);

            string examplePropertyUrl = string.Empty;
            string examplePropertyIdSetting = SettingsService.GetSettingValue(BusinessLogic.Enums.SettingKeyName.ExamplePropertyId); // obtain setting with exmaple property id

            var blobUrl = ConfigurationService.GetKeyValue(CloudConfigurationKeys.StorageBlobUrl).TrimEnd("/".ToCharArray());

            // if setting doesn't exists, don't show the link
            if (!String.IsNullOrWhiteSpace(examplePropertyIdSetting))
            {
                int examplePropertyId;

                if (int.TryParse(examplePropertyIdSetting, out examplePropertyId))
                {
                    var exampleProperty = PropertiesService.GetProperties().Where(p => p.PropertyID == examplePropertyId).SingleOrDefault();

                    if (exampleProperty != null)
                        examplePropertyUrl = "/PropertyDetail/PropertyDetails/" + exampleProperty.PropertyID;
                }
            }

            ViewBag.ExamplePropertyUrl = examplePropertyUrl;
            ViewBag.TopNavigationSection = new MvcHtmlString(string.Format("<h1>{0}</h1>", ExtranetApp.Resources.Views.HomeOwner.Index_Title));

            return View("Index");
        }

        /// <summary>
        /// Displays MyAccount View
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Owner, Property Manager")]
        public ActionResult MyAccount()
        {
            SessionUser sessionUser = this.StateService.CurrentUser;
            List<PropertyWithImages> listPropImage = new List<PropertyWithImages>();
            List<Property> propertyList = GetPropertiesListForLoggedUser();

            string blobContainter = this.ConfigurationService.GetKeyValue(BusinessLogic.Enums.CloudConfigurationKeys.StorageBlobUrl);

            propertyList.ForEach(delegate(Property p)
            {
                var retinaImage = this.PropertiesService.GetPropertyStaticContentByType(p.PropertyID, PropertyStaticContentType.FullScreen_Retina).SingleOrDefault();
                var normalImage = this.PropertiesService.GetPropertyStaticContentByType(p.PropertyID, PropertyStaticContentType.FullScreen).SingleOrDefault();

                PropertyWithImages propWithImg = new PropertyWithImages()
                {
                    Property = p,
                    FullScreenImage = normalImage == null ? null : string.Format("{0}{1}", blobContainter, normalImage.ContentValue),
                    FullScreenImageRetina = retinaImage == null ? null : string.Format("{0}{1}", blobContainter, retinaImage.ContentValue),
                };
                listPropImage.Add(propWithImg);
            });

            MyAccountModel model = new MyAccountModel()
            {
                Owner = GetProfileModel(this.UserService.GetUserByUserId(sessionUser.UserID)),
                PropertyWithImages = listPropImage
            };

            ViewBag.Countries = new SelectList(this.DictionaryCountryService.GetCountries(), "CountryCode2Letters", "CountryNameCurrentLanguage");

            return View(model);
        }

        /// <summary>
        /// Invoked on Homeowner update data request (my account)
        /// </summary>
        /// <param name="model">Update model</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Owner, Property Manager")]
        public ActionResult MyAccount(MyAccountModel model)
        {
            if (ModelState.IsValid)
            {
                UpdateUserData(model.Owner);
                return RedirectToAction("MyAccount");
            }
            else
            {
                SessionUser sessionUser = this.StateService.CurrentUser;
                List<PropertyWithImages> listPropImage = new List<PropertyWithImages>();

                List<Property> propertyList = GetPropertiesListForLoggedUser();

                string blobContainter = this.ConfigurationService.GetKeyValue(BusinessLogic.Enums.CloudConfigurationKeys.StorageBlobUrl);

                propertyList.ForEach(delegate(Property p)
                {
                    var retinaImage = this.PropertiesService.GetPropertyStaticContentByType(p.PropertyID, PropertyStaticContentType.FullScreen_Retina).SingleOrDefault();
                    var normalImage = this.PropertiesService.GetPropertyStaticContentByType(p.PropertyID, PropertyStaticContentType.FullScreen).SingleOrDefault();

                    PropertyWithImages propWithImg = new PropertyWithImages()
                    {
                        Property = p,
                        FullScreenImage = normalImage == null ? null : string.Format("{0}{1}", blobContainter, normalImage.ContentValue),
                        FullScreenImageRetina = retinaImage == null ? null : string.Format("{0}{1}", blobContainter, retinaImage.ContentValue),
                    };
                    listPropImage.Add(propWithImg);
                });

                MyAccountModel newModel = new MyAccountModel()
                {
                    Owner = GetProfileModel(this.UserService.GetUserByUserId(sessionUser.UserID)),
                    PropertyWithImages = listPropImage
                };

                ViewBag.Countries = new SelectList(this.DictionaryCountryService.GetCountries(), "CountryCode2Letters", "CountryNameCurrentLanguage");

                return View(newModel);
            }
        }

        /// <summary>
        /// Display Places View
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Owner, Property Manager")]
        public ActionResult Places()
        {
            var sessionUser = this.StateService.CurrentUser;

            var propertyList = GetPropertiesListForLoggedUser();
            string blobContainter = this.ConfigurationService.GetKeyValue(BusinessLogic.Enums.CloudConfigurationKeys.StorageBlobUrl);

            List<PlacesModel> model = new List<PlacesModel>();
            foreach (var property in propertyList)
            {
                PlacesModel m = new PlacesModel()
                {

src/OTP/ExtranetApp/Views/Shared/Partial/AudioPlayer.cshtml
@using ExtranetApp.Resources.Views;

<div id="audioBG"></div>
<div id="play_bt"></div>
<div id="pause_bt"></div>	

src/OTP/ExtranetApp/Views/Shared/Partial/CancellationPolicy.cshtml
@using ExtranetApp.Resources.Guest;
@using ExtranetApp.Resources.Home;
@using ExtranetApp.Resources;
@model DataAccess.Reservation
@{
    System.Globalization.CultureInfo cInfoUser = Model.User.DictionaryCulture.CultureInfo;
    DateTime mostRestrictiveArrivalDate = (DateTime)ViewData["MostRestrictiveArrivalDate"];
    double diffrenceBetweenArrivalAndNow = (mostRestrictiveArrivalDate - DateTime.Now).TotalDays;
    double diffrenceBetweenBookingAndNow = (DateTime.Now - Model.BookingDate).TotalHours;
    double diffrenceBetweenBookingAndArrival = (mostRestrictiveArrivalDate - Model.BookingDate).TotalHours;
    string cancellationText;       
    DateTime h24AfterBooking = Model.BookingDate.AddHours(24);
    DateTime d30BeforeArrival = mostRestrictiveArrivalDate.AddDays(-30);
    

    if (diffrenceBetweenArrivalAndNow >= 30)
    {
        if (diffrenceBetweenBookingAndNow <= 24)
        {
            cancellationText = String.Format(CommonFrontEnd.CancellationPolicyLessThen24HoursFullRefund, h24AfterBooking.ToString("hh:mm tt, MMMM dd, yyyy", cInfoUser))
                + "</br>" + String.Format(CommonFrontEnd.CancellationPolicyHoursHalfRefund, d30BeforeArrival.ToString("hh:mm tt, MMMM dd, yyyy", cInfoUser))
                + "</br>" + String.Format(CommonFrontEnd.CancellationPolicyWhatIfAfterTime, d30BeforeArrival.ToString("hh:mm tt, MMMM dd, yyyy", cInfoUser));
        }
        else
        {
            cancellationText = String.Format(CommonFrontEnd.CancellationPolicyHoursHalfRefund, d30BeforeArrival.ToString("hh:mm tt, MMMM dd, yyyy", cInfoUser))
                + "</br>" + String.Format(CommonFrontEnd.CancellationPolicyWhatIfAfterTime, d30BeforeArrival.ToString("hh:mm tt, MMMM dd, yyyy", cInfoUser));
        }
    }
    else
        if (diffrenceBetweenArrivalAndNow >= 15)
        {
            if (diffrenceBetweenBookingAndNow <= 24)
            {
                cancellationText = String.Format(CommonFrontEnd.CancellationPolicyLessThen24HoursFullRefund, h24AfterBooking.ToString("hh:mm tt, MMMM dd, yyyy", cInfoUser))
                    + "</br>" + String.Format(CommonFrontEnd.CancellationPolicyWhatIfAfterTime, h24AfterBooking.ToString("hh:mm tt, MMMM dd, yyyy", cInfoUser));
            }
            else
            {
                cancellationText = CommonFrontEnd.CancellationPolicyTryingToResell;
            }
        }
        else
        {
            cancellationText = CommonFrontEnd.CancellationPolicyTryingToResell;
        }
}
@Html.Raw(cancellationText)

src/OTP/ExtranetApp/Views/Shared/Partial/DateFromWrongDialog.cshtml
<div id="date-from-wrong-dialog" class="popup-dialog" title="@ExtranetApp.Resources.Home.Index.DateFromWrongDialog_Title"> 
    @ExtranetApp.Resources.Home.Index.DateFromWrongDialog_Description
</div>

src/OTP/ExtranetApp/Views/Shared/Partial/DateUntilWrongDialog.cshtml
<div id="date-until-wrong-dialog" class="popup-dialog" title="@ExtranetApp.Resources.Home.Index.DateUntilWrongDialog_Title"> 
    @ExtranetApp.Resources.Home.Index.DateUntilWrongDialog_Description <span class="date"></span>
</div>

src/OTP/ExtranetApp/Views/Shared/Partial/GuestReviews_ReviewList.cshtml
@using ExtranetApp.Resources.Home;
@using Common.Extensions;

@model IEnumerable<DataAccess.GuestReview>


@foreach (var review in Model)
{
    <div class="widget-section">
        <div class="widget table-like">

            <div class="description-features">
                <div class="widget-content">
                    <p>@review.User.FullName,</p>
                    @if (review.ReviewDate > DateTime.Now.AddMonths(-1))
                    {
                        var timeSpan = DateTime.Now - review.ReviewDate;
                                              
                        <p>
                            @if (timeSpan.Days == 0 && timeSpan.Hours == 0)
                            {
                                @timeSpan.Minutes <span></span>@PropertyDetails.ViewGuestReviews_MinutesAgo 
                            }
                            @if (timeSpan.Hours > 0 && timeSpan.Days == 0)
                            {
                                @timeSpan.Hours <span></span>@PropertyDetails.ViewGuestReviews_HoursAgo 
                            }
                            @if (timeSpan.Days > 0)
                            {
                                @timeSpan.Days <span></span>@PropertyDetails.ViewGuestReviews_DaysAgo 
                            }
                            <span></span>@PropertyDetails.ViewGuestReviews_Ago
                        </p>
                               
                    }
                    else
                    {
                        <p>@review.ReviewDate.ToLocalizedDateString()</p>       
                    }
                </div>
            </div>

            <div class="description-features second">
                <div class="widget-content">
                    <h2 style="margin-bottom: 0px;">
                        @review.ReviewTitle
                    </h2>
                    <div>
                        @review.ReviewContent
                    </div>
                </div>
                <div class="widget-content guestStarRatingSection">
                    <a href="javascript:void()" class="review-group-link" review-group-id="@review.GuestReviewID">
                        @for (int i = 1; i <= 5; i++)
                        {
                            if (i <= review.OverallRating)
                            {
                            <img src="@Url.Content("~/images/otp/star_blue_full.png")" />
                            }
                            else
                            {
                            <img src="@Url.Content("~/images/otp/star_blue_empty.png")" />
                            }
                        }
                    </a>
                </div>
            </div>
            <div style="clear: both"></div>

        </div>
    </div>
    
    <div class="review-dialog property-dialog" review-group-id="@review.GuestReviewID">
        <div class="guestReviewRatings">
            <h3>@PropertyDetails.ViewGuestReviews_Quality</h3>
            @for (int i = 1; i <= 5; i++)
            {
                if (i <= review.Satisfaction_Experience)
                {
                <img src="@Url.Content("~/images/otp/star_blue_full.png")" />
                }
                else
                {
                <img src="@Url.Content("~/images/otp/star_blue_empty.png")" />
                }
            }
        </div>
        <div class="guestReviewRatings">
            <h3>@PropertyDetails.ViewGuestReviews_Cleanliness</h3>
            @for (int i = 1; i <= 5; i++)
            {
                if (i <= review.Satisfaction_Cleanliness)
                {
                <img src="@Url.Content("~/images/otp/star_blue_full.png")" />
                }
                else
                {
                <img src="@Url.Content("~/images/otp/star_blue_empty.png")" />
                }
            }
        </div>
        <div class="guestReviewRatings">
            <h3>@PropertyDetails.ViewGuestReviews_Location</h3>
            @for (int i = 1; i <= 5; i++)
            {
                if (i <= review.Satisfaction_Location)
                {
                <img src="@Url.Content("~/images/otp/star_blue_full.png")" />
                }
                else
                {
                <img src="@Url.Content("~/images/otp/star_blue_empty.png")" />
                }
            }
        </div>
        <div style="clear: both"></div>
    </div>
}

src/OTP/ExtranetApp/Views/Shared/Partial/JoinGuest.cshtml
@using ExtranetApp.Resources.Views;
@using ExtranetApp.Resources.Models;
@model ExtranetApp.Models.Account.JoinModel

@{
    ViewBag.Title = Shared.JoinPopup_Header;
}

<div id="joinBlockPopup">
    <hgroup class="title">
        <h1>@ViewBag.Title</h1>
    </hgroup>   
    
    <section id="joinForm">
    @using (Ajax.BeginForm("Join", "Account", new AjaxOptions() { UpdateTargetId = "blockJoin", OnSuccess = "onJoinComplete" })) 
    {
        <div style="color: red;" id="blockJoin">
        </div>
         <fieldset>
            <ul>
                <li>
                    @Html.TextBoxFor(m => m.FirstName, new {@class = "input-textarea", defaultText = Join.JoinModel_FirstName } )<br />
                    @Html.ValidationMessageFor(m => m.FirstName)
                </li>
                <li>
                    @Html.TextBoxFor(m => m.LastName, new {@class = "input-textarea", defaultText = Join.JoinModel_LastName } )<br />
                    @Html.ValidationMessageFor(m => m.LastName)
                </li>
                <li>
                     @Html.TextBoxFor(m => m.Email, new {@class = "input-textarea", defaultText = Join.JoinModel_Email } )<br />
                    @Html.ValidationMessageFor(m => m.Email)
                </li>
            </ul>
            <input type="submit" value="@Shared.JoinPopup_Header" class="input-submit" style="width:70% !important;" />
        </fieldset>
    }
    </section>
</div>

src/OTP/ExtranetApp/Views/Shared/Partial/Login.cshtml
@using ExtranetApp.Resources.Views;
@model ExtranetApp.Models.Account.LoginModel

@{
    ViewBag.Title = @Shared.LoginPopup_Header;
}


<div id="loginBlockPopup">
<hgroup class="title">
    <a href="javascript:void;" class="joinLink"><h1>@ViewBag.Title</h1></a>
</hgroup>
    
<section id="loginForm">
<h2>@Shared.Login_Header</h2>
@using (Ajax.BeginForm("LoginAsGuest", "Account", new AjaxOptions() { UpdateTargetId = "blockLogin", OnSuccess = "onTestComplete" })) 
{
    <div style="color: red;" id="blockLogin">
    </div>
    <fieldset>
        <legend></legend>        
        <ul>
            <li>                
                @Html.TextBoxFor(m => m.Email, new {@class = "input-textarea", defaultText = Shared.Login_Input_Email })
                @Html.ValidationMessageFor(m => m.Email)
            </li>
            <li>                
                @Html.PasswordFor(m => m.Password, new {@class = "input-textarea", defaultText = Shared.Login_Input_Password })
                @Html.ValidationMessageFor(m => m.Password)
            </li>
        </ul>
        <input type="submit" value="@Shared.Login_Button_Submit" class="input-submit"  />
    </fieldset>
    <p>
        @Html.ActionLink(Shared.Login_ForgotPassword, "ForgotPassword", "Account")
    <br />
        
        <a href="javascript:void();" class="joinLink">@Shared.Login_Link_Join</a>
    </p>
}
</section>
</div>

src/OTP/ExtranetApp/Views/Shared/Partial/LoginButton.cshtml
@using ExtranetApp.Resources.Views;
@using BusinessLogic.Managers

@if (SessionManager.IsAuthenticated())
{
    if (SessionManager.CurrentUser.LoggedInRole.RoleLevel == (int)DataAccess.Enums.RoleLevel.Guest)
    {
    @Html.ActionLink(String.Format(Shared.LoginButton_Welcome, SessionManager.CurrentUser.FullName), "MyTrips", "Guest")
    }
    else if (SessionManager.CurrentUser.LoggedInRole.RoleLevel == (int)DataAccess.Enums.RoleLevel.KeyManager)
    {                
    @Html.ActionLink(String.Format(Shared.LoginButton_Welcome, SessionManager.CurrentUser.FullName), "KeyManagement", "Homeowner")
    }
    else
    {             
    @Html.ActionLink(String.Format(Shared.LoginButton_Welcome, SessionManager.CurrentUser.FullName), "Places", "Homeowner")
    }
}
else
{
    <a href="javascript:void();" id="showLoginLink">@Shared.LoginButton_Link_LoginJoin</a>
@Html.ActionLink(Shared.LoginButton_Link_Homeowners, "AboutJoin", "HomeOwner")
}

src/OTP/ExtranetApp/Views/Shared/Partial/Logout.cshtml
@using ExtranetApp.Resources.Views;
@using BusinessLogic.Managers

@if (SessionManager.IsAuthenticated())
{
    using (Html.BeginForm("Logout", "Account", FormMethod.Post, new { id = "logoutForm", style = "display: none;", @class = "single-submit-form" })) 
    {
        @Html.AntiForgeryToken()                    
    }
    <a id="logoutLink" class="logout-link" href="javascript:void(0)">@Shared.Logout_Logout</a>    
}

src/OTP/ExtranetApp/Views/Shared/Partial/MenuBar.cshtml
@using ExtranetApp.Resources.Views;
@using BusinessLogic.Managers

<nav>
    <div class="navigation">
        @if (SessionManager.IsAuthenticated())
        {
            <ul id="mobile-menu-1">
                <li><a href="#">Welcome @SessionManager.CurrentUser.FullName!</a></li>
                @if (SessionManager.CurrentUser.LoggedInRole.RoleLevel == (int)DataAccess.Enums.RoleLevel.Guest)
                {                    
                    <li><a href="@Url.Action("Profile", "Guest")">@Shared.Links_Profile</a></li>
                    <li><a href="@Url.Action("Mytrips", "Guest")">@Shared.Links_MyTrips</a></li>                    
                    <li><a href="@Url.Action("OnSiteServices", "Guest")">@Shared.Links_OnStieServices</a></li>
                }
                else if (SessionManager.CurrentUser.LoggedInRole.RoleLevel == (int)DataAccess.Enums.RoleLevel.Owner)
                {
                    <li><a href="@Url.Action("MyAccount", "Homeowner")">@Shared.Links_Owner</a></li>
                    <li><a href="@Url.Action("Places", "Homeowner")">@Shared.Links_Places</a></li>
                    <li><a href="@Url.Action("KeyManagement", "Homeowner")">@Shared.Links_KeyManagement</a></li>                   
                    <li><a href="@Url.Action("Contact", "Homeowner")">@Shared.Links_Contact</a></li>
                }
                <li>@Html.ActionLink(@Shared.Links_ChangePassword, "ChangePassword", "Account")</li>
                <li>@Html.Partial("Partial/Logout")</li>
            </ul>
        }
        else
        {
            <div class="homeowner-page-title" style="width: 70%; float: left">
                @ViewBag.TopNavigationSection
            </div>
        }
        @Html.Partial("Partial/AudioPlayer")
    </div>
</nav>

src/OTP/ExtranetApp/Views/Shared/Partial/SearchFinalScoreDetails.cshtml
@model ExtranetApp.Models.Home.FinalScoreDetailsModel
@using ExtranetApp.Resources.Views;

<div>
    <div id="scrollable-x-area">
    <table>
        @*Guests*@
        @if (Model.Details.UnitGuests.HasValue)
        {        
            <tr>
                <td>@string.Format(Shared.ScoreDetails_Guests, Model.Details.UnitGuests.Value.ToString(), Model.SearchFilterGuests.Value.ToString())</td>
            </tr>
        }
        @*Bedrooms*@
        @if (Model.Details.UnitBedrooms.HasValue)
        {        
            <tr>
                <td>@string.Format(Shared.ScoreDetails_Bedrooms, Model.Details.UnitBedrooms.Value.ToString(), Model.SearchFilterBedrooms.Value.ToString())</td>
            </tr>
        }            
        @*Bathromms*@
        @if (Model.Details.UnitBathrooms.HasValue)
        {        
            <tr>
                <td>@string.Format(Shared.ScoreDetails_Bathrooms, Model.Details.UnitBathrooms.Value.ToString(), Model.SearchFilterBathrooms.Value.ToString())</td>
            </tr>
        }            
        @*PropertyType*@
        @if (Model.Details.NotMatchedPropertyTypes != null)
        {        
            <tr>
                <td>@string.Format(Shared.ScoreDetails_PropertyTypes, Model.Details.PropertyType, string.Join(", ", Model.Details.NotMatchedPropertyTypes))</td>
            </tr>
        }
        @*Amenities*@
        @if (Model.Details.NotMatchedAmenities != null)
        {        
            <tr>
                <td>@string.Format(Shared.ScoreDetails_Amenities, string.Join(", ", Model.Details.NotMatchedAmenities))</td>
            </tr>
        }            
        @*Expriences*@
        @if (Model.Details.NotMatchedExperiences != null)
        {        
            <tr>
                <td>@string.Format(Shared.ScoreDetails_Experiences, string.Join(", ", Model.Details.NotMatchedExperiences))</td>
            </tr>
        }
    </table>
    </div>
</div>