src/OTP/ExtranetApp/Models/Guest/CancelTripModel.cs
using DataAccess;
using DataAccess.CustomObjects;
using ModelMetadataExtensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;


namespace ExtranetApp.Models.Guest
{
    [Serializable]
    [MetadataConventionsAttribute(ResourceType = typeof(Resources.Models.UserProfile))]
    public class CancelTripModel
    {
        public Reservation reservation { get; set; }
        public IEnumerable<String> Thumbnails { get; set; }
        public User User { get; set; }
        public Int32 ReservationId { get; set; }
        public String errorMessage { get; set; }
    }
}

src/OTP/ExtranetApp/Models/Guest/CancellationConfirmationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExtranetApp.Models.Guest
{
    public class CancellationConfirmationModel
    {
        public String userEmail;
        public String message;
        public String cancellationCode;
    }
}

src/OTP/ExtranetApp/Models/Guest/ChangeTripDateModel.cs
using DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExtranetApp.Models.Guest
{
    [Serializable]
    public class ChangeTripDateModel
    {
        public int reservationId { get; set; }
        public Reservation reservation { get; set; }
        public IEnumerable<String> Thumbnails { get; set; }
        public User user { get; set; }
        public DateTime DateArrival { get; set; }
        public DateTime DateDeparture { get; set; }

    }
}

src/OTP/ExtranetApp/Models/Guest/GuestProfileModel.cs
using ExtranetApp.Extensions;
using ExtranetApp.Resources.Models;
using ModelMetadataExtensions;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExtranetApp.Models.Guest
{
    // All localization strings are taken from Common resx file.
    // Localization Names with HomeownerModel_<PropertyName>_<Attribute> 
    // (HomeownerModel_ConfirmPassword_Compare)
    [Serializable]
    [MetadataConventionsAttribute(ResourceType = typeof(Resources.Models.UserProfile))]
    public class GuestProfileModel
    {
        public int UserId { get; set; }

        [Required]
        [StringLength(250)]
        public string FirstName { get; set; }

        [Required]
        [StringLength(250)]
        public string LastName { get; set; }

        [StringLength(250)]
        [RegularExpression(@"\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*")]
        public string Email { get; set; }

        [StringLength(50)]
        public string PhoneNumber { get; set; }

        [StringLength(250)]
        public string AddressLine1 { get; set; }

        [StringLength(250)]
        public string AddressLine2 { get; set; }

        [StringLength(250)]
        public string State { get; set; }

        [StringLength(250)]
        public string City { get; set; }

        [StringLength(250)]
        public string ZIPCode { get; set; }

        [Required(ErrorMessageResourceName = "Validation_Required", ErrorMessageResourceType = typeof(ValidationShared))]
        public int Country { get; set; }

        public string CountryName { get; set; }

        public List<DataAccess.GuestPaymentMethod> CreditCards { get; set; }

        public string FullName { get; set; }

        [Required(ErrorMessageResourceName = "Validation_Required", ErrorMessageResourceType = typeof(ValidationShared))]
        public int UserCulture { get; set; }

        public string UserCultureName { get; set; }

        public int CreditCardToDelete { get; set; }

        public IEnumerable<int> CreditCardsInUse { get; set; }

        public bool SendInfoFavoritePlaces { get; set; }

        public bool SendNews { get; set; }

        public bool SendMePromotions { get; set; }
    }
}

src/OTP/ExtranetApp/Models/Guest/InvoiceDetailsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExtranetApp.Models.Guest
{
    [Serializable]
    public class InvoiceDetailsModel
    {
        public DataAccess.CustomObjects.PropertyDetailsInvoice invoiceDetail;
        public decimal originalReservationTotalPrice;
    }
}

src/OTP/ExtranetApp/Models/Guest/MyTripsModel.cs
using DataAccess;
using ModelMetadataExtensions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using DataAccess.CustomObjects;

namespace ExtranetApp.Models.Guest
{
    [Serializable]
    [MetadataConventionsAttribute(ResourceType = typeof(Resources.Models.UserProfile))]
    public class MyTripsModel
    {
        public IEnumerable<ReservationForUser> reservations { get; set; }
        public User User { get; set; }
    }
}

src/OTP/ExtranetApp/Models/Guest/TripDetailModel.cs
using BusinessLogic.Objects.StaticContentRepresentation;
using DataAccess;
using System;
using System.Collections.Generic;

namespace ExtranetApp.Models.Guest
{
    [Serializable]
    public class TripDetailModel
    {
        public string AlertCode { get; set; }
        public string AlertLocation { get; set; }
        public IEnumerable<PropertyStaticContent> ArrivalInformations { get; set; }
        public IEnumerable<DirectionToAirport> Directions { get; set; }
        public User KeyMenager { get; set; }
        public int KeyProcess { get; set; }
        public int LengthOfStay { get; set; }
        public string LockBoxCode { get; set; }
        public string LockBoxLocation { get; set; }
        public IEnumerable<PropertyStaticContent> Parkings { get; set; }
        public decimal PricePerNight { get; set; }
        public Reservation Reservation { get; set; }
        public int ReservationId { get; set; }
        public User User { get; set; }
        public IEnumerable<UnitStaticContent> WifiName { get; set; }
        public IEnumerable<UnitStaticContent> WifiPass { get; set; }

        public Reservation mostExpensiveReservation { get; set; }
    }
}

src/OTP/ExtranetApp/Controllers/PropertyDetailController.cs
using BusinessLogic.Enums;
using BusinessLogic.Managers;
using BusinessLogic.ServiceContracts;
using DataAccess;
using DataAccess.CustomObjects;
using DataAccess.Enums;
using ExtranetApp.Models;
using ExtranetApp.Models.PropertyDetails;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ExtranetApp.Controllers
{
    public class PropertyDetailController : BaseController
    {
        #region Ctor

        public PropertyDetailController(IPropertiesService propertiesService, 
            IUnitsService unitsService, 
            IAmenityGroupsService amenityGroupsService,
            IConfigurationService configurationService,
            IPropertyAddOnsService propertyAddOnsService,
            ITaxesService taxesService,
            IBookingService bookingService,
            IAppliancesService appliancesService)
            : base(new Dictionary<Type, object>() 
                {
                    { typeof(IPropertiesService), propertiesService }, 
                    { typeof(IUnitsService), unitsService }, 
                    { typeof(IAmenityGroupsService), amenityGroupsService }, 
                    { typeof(IConfigurationService), configurationService }, 
                    { typeof(IPropertyAddOnsService), propertyAddOnsService }, 
                    { typeof(ITaxesService), taxesService }, 
                    { typeof(IBookingService), bookingService },
                    { typeof(IAppliancesService), appliancesService },
                })
        {
        }

        #endregion

        #region Views

        /// <summary>
        /// Shows property details page
        /// </summary>
        /// <param name="id">Unit id of the selected property</param>
        /// <param name="token">Sign Off token</param>
        /// <returns>Property details view</returns>
        public ActionResult PropertyDetails(int id = 1, string token = "")
        {
            int numberOfUnits = 0;

            PropertyDetailsModel model = new PropertyDetailsModel();                       

            model.StorageUrl = this.ConfigurationService.GetKeyValue(CloudConfigurationKeys.StorageBlobUrl).TrimEnd("/".ToCharArray());
            model.Unit = this.UnitsService.GetUnitById(id);
            Int32 propertyId = this.PropertiesService.GetPropertyIdByUnitId(id);
            Property property = this.PropertiesService.GetPropertyById(propertyId, out numberOfUnits);

            /// We can only show property that is active
            if (!property.PropertyLive)
            {
                if (!token.Equals(property.SignOffCode))
                {
                    throw new Exception("Property is no active! You cannot visit it yet!");
                }
            } 
            
            model.NumberOfPropertyUnits = numberOfUnits;
            var staticPropertyInfo = this.PropertiesService.GetPropertyStaticContentInfo(propertyId).AsEnumerable();
            var staticUnitInfo = this.UnitsService.GetUnitStaticContentInfo(id).AsEnumerable();

            model.PropertyRating = property.StarRating;

            model.Property = property;
            var images = GetPropertyStaticContentByType(PropertyStaticContentType.FullScreen, staticPropertyInfo, false);
            var galleryImages = GetPropertyStaticContentByType(PropertyStaticContentType.GalleryImage, staticPropertyInfo, false);
            string blobContainter = this.ConfigurationService.GetKeyValue(BusinessLogic.Enums.CloudConfigurationKeys.StorageBlobUrl);
            model.PropertyImages = images.Select(s => string.Format("{0}{1}", blobContainter, s));
            model.GalleryImages = galleryImages.Select(s => string.Format("{0}{1}", blobContainter, s));
            model.SquareFootage = GetPropertyStaticContentByType(PropertyStaticContentType.SquareFootage, staticPropertyInfo, true).FirstOrDefault();
            model.KitchenDesc = GetUnitStaticContentByType(UnitStaticContentType.KitchenAndLaundry, staticUnitInfo, true);
            model.BathroomsDesc = GetUnitStaticContentByType(UnitStaticContentType.Bathrooms, staticUnitInfo, true);
            model.BedroomsDesc = GetUnitStaticContentByType(UnitStaticContentType.Bedrooms, staticUnitInfo, true);
            model.LivingArea = GetUnitStaticContentByType(UnitStaticContentType.LivingAreasAndDining, staticUnitInfo, true);
            model.Features = GetPropertyStaticContentByType(PropertyStaticContentType.Feature, staticPropertyInfo, true);
            model.DistanceFormAttractions = GetPropertyStaticContentByType(PropertyStaticContentType.DistanceToMainAttraction, staticPropertyInfo, true);

            model.ApplianceGroups = this.AppliancesService.GetApplianceGroups().ToList();
            model.Appliances = this.UnitsService.GetUnitAppliances(id).ToList();
            model.GuestReviews = this.PropertiesService.GetPropertyGuestReviews(propertyId);
            model.FloorPlans = this.PropertiesService.GetPropertyFloorPlans(propertyId);
            model.DestinationDetails = model.Property.Destination;

            var propertyUnitName = new StringBuilder( model.Property.PropertyNameCurrentLanguage );

            if (model.NumberOfPropertyUnits > 1)
            {
                propertyUnitName = propertyUnitName.Append(" / ").Append(model.Unit.UnitTitleCurrentLanguage);
            }

            model.PropertyUnitName = propertyUnitName.ToString();


            //var groups = this.PropertiesService.GetAmenityGroupsByPropertyId(propertyId);
            var amenities = this.PropertiesService.GetPropertyAmenitiesByPropertyId(propertyId).ToList();
            model.Amenities = GetAmenitiesForAmenityGroups( amenities);
            return View(model);
        }

        /// <summary>
        /// View redendered for homeowner link to preview property in frontend
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult SignOffConfirm(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                throw new Exception("No token to validate");
            }

            Property property = this.PropertiesService.GetPropertyBySingOffToken(id);
            if (property == null)
            {
                throw new Exception("Cannot retrieve property - token is invalid!");
            }

            SignOffModel model = new SignOffModel()
            {
                Property = property,
                SignOffToken = id
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SignOffConfirm(SignOffModel model)
        {
            Property property = this.PropertiesService.GetPropertyBySingOffToken(model.SignOffToken);
            if (property == null)
            {
                throw new Exception("Cannot retrieve property - token is invalid!");
            }
            property.SignOffCode = string.Empty;
            property.PropertyLive = true;

            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Shows 360 view
        /// </summary>
        /// <param name="id">Property id</param>
        /// <param name="panoramaId">Panorama id</param>
        /// <returns></returns>
        public ActionResult PanoramaView(int id, int panoramaId)
        {
            string blobContainter = this.ConfigurationService.GetKeyValue(CloudConfigurationKeys.StorageBlobUrl).TrimEnd("/".ToCharArray());            
            var floorPlans = this.PropertiesService.GetPropertyFloorPlans(id);            

            PanoramaModel model = new PanoramaModel()
            {
                Panorama = floorPlans.SelectMany(f => f.Panoramas).Where(s => s.Id.Equals(panoramaId)).SingleOrDefault(),
                FloorPlan = floorPlans.Where(f => f.Panoramas.Any(s => s.Id.Equals(panoramaId))).SingleOrDefault(),
                Property = this.PropertiesService.GetPropertyById(id),
                StorageUrl = blobContainter
            };
            
            return View(model);
        }        

        #endregion

        #region PartialViews

        /// <summary>
        /// Retrieves Guest Reviews sorted by parameter
        /// </summary>
        /// <param name="propertyId">Id of the property</param>
        /// <param name="sortType">Type of the sort - direction and column</param>
        /// <returns>Property Guest Reviews Partial View</returns>
        public PartialViewResult GetSortedPropertyReviews(int propertyId, string sort = "")
        {
            SortByType sortType = String.IsNullOrEmpty(sort) ? SortByType.TimeDesc : ((SortByType)Enum.Parse(typeof(SortByType), sort, true));

            var guestReviews = this.PropertiesService.GetPropertyGuestReviews(propertyId);
            SortGuestReviewsBy(sortType, ref guestReviews);

            return PartialView("Partial/GuestReviews_ReviewList", guestReviews);
        }

        /// <summary>
        /// Retrieves Invoice Details for currently selected Unit
        /// </summary>
        /// <param name="unitId">Id of the Unit</param>
        /// <param name="dateFrom">Date of customer arrival</param>
        /// <param name="dateUntil">Date of the customer leave</param>
        /// <returns>Partial View with invoice details data</returns>
        public PartialViewResult GetInvoiceDetails(int unitId, int propertyId, DateTime dateFrom, DateTime dateUntil)
        {
            var result = this.BookingService.CalculateInvoice(propertyId, unitId, dateFrom, dateUntil);


            return PartialView("Partial/PropertyDetails_InvoiceSection", result);
        }

        /// <summary>
        /// Retrieves Partial view InvoiceSection for given invoice data
        /// </summary>
        /// <param name="InvoiceDetails">Calculated invoice data</param>
        /// <returns>Partial View with invoice details data</returns>

src/OTP/ExtranetApp/Views/Guest/CancelTrip.cshtml
@using ExtranetApp.Resources.Views;
@using ExtranetApp.Resources.Models;
@using DataAccess;
@using System.Globalization;
@using ExtranetApp.Resources.Guest;
@using DataAccess.CustomObjects;
@using DataAccess.Enums;

@model ExtranetApp.Models.Guest.CancelTripModel

@{
    ViewBag.Title = Shared.PageTitle;
}


@Styles.Render("~/css/otp_MyTrips.css")


@section Scripts
{
    @Scripts.Render("~/js/jquery.cycle.all.js")
    @Scripts.Render("~/js/Views/otp_CancelTrip.js")
    <script>
        var cancelDialogText = '@MyTrips.CancelConfirmation';
        var cancelDialogNoButton = '@MyTrips.NoBtn';
        var cancelDialogYesButton = '@MyTrips.YesBtn';
        var cancelDialogTitle = '@MyTrips.ConfirmCancelDialogTitile';
    </script>
}


@*@Html.ActionLink(Guest.Mytrips_Link_Back, "Index", "Home")*@

<section id="myTrips" class="content-center">
    @if (BusinessLogic.Managers.SessionManager.IsAuthenticated())
    {
    <div id="myTrips_page_title" class="container">
            <h2 class="page-title">
                @MyTrips.cancelTrip
            </h2>
    </div>

    <div id="myTrips_main_wrap" class="container" style="margin-top: 0px;">
    <div id="CurrentTrips" class="selected">

        <div class="trip">
            <div class="tripTitle">
				    <h4>@Model.reservation.Property.PropertyNameCurrentLanguage, @Model.reservation.Property.City, @Model.reservation.Property.State, 
                        
                            @Model.reservation.DateArrival.ToString("MMMM", CultureInfo.CreateSpecificCulture(Model.User.DictionaryCulture.CultureCode)) 
                            @Model.reservation.DateArrival.ToString("dd")
                            @if (Model.reservation.DateArrival.Year != Model.reservation.DateDeparture.Year)
                            {
                                <text> </text>@Model.reservation.DateArrival.ToString("yyyy")
                            }
                            - 
                        @if (Model.reservation.DateArrival.Month != Model.reservation.DateDeparture.Month)
                        {
                            @Model.reservation.DateDeparture.ToString("MMMM", CultureInfo.CreateSpecificCulture(Model.User.DictionaryCulture.CultureCode))<Text> </Text>   
                        }
                        @Model.reservation.DateDeparture.ToString("dd"), @Model.reservation.DateDeparture.Year
				    </h4>
		    </div>
            <div class="two_third first column_container portfolio_image">

                <div class="thumbnail_container">
                    @foreach (var thumbnail in Model.Thumbnails)
                    {
                        <img class="propertyImage" src="@thumbnail" />
                    }
                </div>
                <div class="tripInfo">
                    @{
                    TimeSpan length = Model.reservation.DateDeparture - Model.reservation.DateArrival;
                    }
                    <p>@length.Days @ExtranetApp.Resources.Home.PropertyDetails.Section_Invoice_NumberOfNights</p>
                    <p>@MyTrips.totalCost @(Model.reservation.TotalPrice.ToString("c", CultureInfo.CreateSpecificCulture(Model.reservation.Property.DictionaryCulture.CultureCode)))</p>
                    
                    
                    <p>@Html.ActionLink(MyTrips.invoice, "GetInvoiceDocument", new { id = Model.reservation.ReservationID }, new { target = "_blank" })
                        @if (Model.reservation.TripBalance == 0)
                        {  
                            @MyTrips.PaidFull
                        }
                        else if (Model.reservation.TripBalance + Model.reservation.TotalPrice == 0)
                        {
                            @MyTrips.Unpaid
                        }
                        else
                        {
                            @MyTrips.PaidFifty
                        }
                        </p>

                    <p>@MyTrips.resDate @Model.reservation.BookingDate.ToString("MMMM dd, yyyy", CultureInfo.CreateSpecificCulture(Model.User.DictionaryCulture.CultureCode))</p>
                </div>
            </div>
            <div class="one_third">
                <h3>@MyTrips.cancellationTerms</h3>
                <div class="cancellationTerms">
                    @using (Html.BeginForm("CancelTripConfirmed", "Guest", FormMethod.Post, new { @class = "single-submit-form", id = "frmCancelRes" }))
                    {
                        {
                            double diffrenceBetweenBookingAndNow = (DateTime.Now - Model.reservation.BookingDate).TotalHours;
                            double diffrenceBetweenArrivalAndNow = (Model.reservation.DateArrival - DateTime.Now).TotalDays;
                            
                            @Html.Partial("Partial/CancellationPolicy", Model.reservation, new ViewDataDictionary {{"MostRestrictiveArrivalDate", ViewBag.MostRestrictiveArrivalDate}})
                            
                        }


                        @Html.HiddenFor(m => m.ReservationId)
                        <div style ="text-align: right;"><input type="submit" id="btnConfirmCancel" value="@MyTrips.cancel" class="input-submit" />
                            <br />
                            @if (Model.errorMessage != null)
                            {
                                <p>@Html.Raw(String.Format(MyTrips.cancellationErrorText, Model.errorMessage))</p>
                            }
                            @Html.ActionLink(@MyTrips.seeCancellationPolicy, "CancellationPolicy", "Home", null, new { target = "_blank" })
                        </div>
                    }                                                  
                </div>
            </div>
            <div class="clear"></div>
        </div>
        
        </div>
        
    </div>
    }
</section>

src/OTP/ExtranetApp/Views/Guest/ConfirmArrivalTime.cshtml
@using ExtranetApp.Resources.Views;

@{
    ViewBag.Title = Shared.PageTitle;
    Layout = "~/Views/Shared/_LayoutDefaultOTP.cshtml"; 
}

<section class="content-center">
    <div class="container" id="main_wrap">
        <h1 class="page-title">@ExtranetApp.Resources.Guest.KeyProcessManagement.Confirmation_Title</h1>
        <div class="content eleven alpha columns">
            <div class="full">
                <p>@ViewBag.Message</p>
                <p>
                    <button style="width:200px !important" class="input-submit" onclick="window.location.href='@Url.Action("Index", "Home")' ">@Account.Activation_Button_Back</button>
                </p>
            </div>
        </div>
    </div>
</section>

src/OTP/ExtranetApp/Views/Guest/Mytrips.cshtml
@using ExtranetApp.Resources.Views;
@using ExtranetApp.Resources.Models;
@using DataAccess;
@using System.Globalization;
@using ExtranetApp.Resources.Guest;
@using DataAccess.CustomObjects;
@using DataAccess.Enums;

@model ExtranetApp.Models.Guest.MyTripsModel

@{
    ViewBag.Title = Guest.Mytrips_Title;
}


@Styles.Render("~/css/otp_MyTrips.css")


@section Scripts
{
    @Scripts.Render("~/js/jquery.cycle.all.js")
    @Scripts.Render("~/js/Views/otp_MyTrips.js")
    @*    @Scripts.Render("~/js/date.js")
    @Scripts.Render("~/js/jquery.uniform.min.js")
    @Scripts.Render("~/js/Views/guestProfile.js")    
    @Scripts.Render("~/js/Views/commonScripts.js")    
    @Scripts.Render("~/js/Views/book.process.js")*@
}


@*@Html.ActionLink(Guest.Mytrips_Link_Back, "Index", "Home")*@


@helper Trip(ReservationForUser res, bool ShowRightPane)
{
    <div class="trip">
        <div class="tripTitle">
            <h4>@Html.ActionLink(res.Property.PropertyNameCurrentLanguage, "PropertyDetails", "PropertyDetail", new { id = res.PropertyID }, new { style = "text-decoration: underline;" }), @res.Property.City, @res.Property.State, 
                        
                            @res.DateArrival.ToString("MMMM", CultureInfo.CreateSpecificCulture(Model.User.DictionaryCulture.CultureCode))
                @res.DateArrival.ToString("dd")
                @if (res.DateArrival.Year != res.DateDeparture.Year)
                {
                    <text> </text>@res.DateArrival.ToString("yyyy")
                }
                - 
                        @if (res.DateArrival.Month != res.DateDeparture.Month)
                        {
@* block for not displaying month name if arrival and departure date are in the same month *@
                            @res.DateDeparture.ToString("MMMM", CultureInfo.CreateSpecificCulture(Model.User.DictionaryCulture.CultureCode))<Text> </Text>   
                        }
                @res.DateDeparture.ToString("dd"), @res.DateDeparture.Year
            </h4>
        </div>
        <div class="two_third first column_container portfolio_image">

            <div class="thumbnail_container">
                @foreach (var thumbnail in res.Thumbnails)
                {
                    <img class="propertyImage" src="@thumbnail" />
                }
            </div>
            <div class="tripInfo">
                @{
                    TimeSpan length = res.DateDeparture - res.DateArrival;
                }
                <p>@length.Days @ExtranetApp.Resources.Home.PropertyDetails.Section_Invoice_NumberOfNights</p>
                <p>@MyTrips.totalCost @(res.TotalPrice.ToString("c", CultureInfo.CreateSpecificCulture(res.Property.DictionaryCulture.CultureCode)))</p>


                <p>@Html.ActionLink(MyTrips.invoice, "GetInvoiceDocument", new { id = res.ReservationID }, new { target = "_blank", style = "text-decoration: underline;" })
                    @if (res.TripBalance == 0)
                    {  
                        @MyTrips.PaidFull
                    }
                    else if (res.TripBalance + res.TotalPrice == 0)
                    {
                        @MyTrips.Unpaid
                    }
                    else
                    {
                        @MyTrips.PaidFifty
                    }
                </p>

                <p>@MyTrips.resDate @res.BookingDate.ToString("MMMM dd, yyyy", CultureInfo.CreateSpecificCulture(Model.User.DictionaryCulture.CultureCode))</p>
            </div>
        </div>
        @if (ShowRightPane)
        {
            <div class="one_third">
                <div class="tripLinks">
                    <p><a href="#">@Html.ActionLink(MyTrips.tripDetail, "TripDetails", new { ReservationId = res.ReservationID })</a></p>
                    <p><a href="#">@Html.ActionLink(MyTrips.changeExtend, "ChangeTripDate", new { resId = res.ReservationID })</a></p>
                    <p><a href="#">@MyTrips.addServices</a></p>
                    @if (res.BookingStatus.Equals((int)BookingStatus.ReceivedBooking) || res.BookingStatus.Equals((int)BookingStatus.FinalizedBooking))
                    {
                        <p><a href="#">@Html.ActionLink(MyTrips.cancelTrip, "CancelTrip", new { ReservationId = res.ReservationID })</a></p>
                    }
                </div>
            </div>
        }
        <div class="clear"></div>
    </div>
}



<section id="myTrips" class="content-center">
    <div id="myTrips_page_title" class="container">
        @if (BusinessLogic.Managers.SessionManager.IsAuthenticated())
        {
            <h3 class="page-title">
                <span id="CurrentLabel" class="selected"><a href="javascript:showCurrent()">@MyTrips.currentTrips</a></span>
                <span id="PastLabel" class="grey"><a href="javascript:showPast()">@MyTrips.pastTrips</a></span>
                <span id="CancelledLabel" class="grey"><a href="javascript:showCancelled()">@MyTrips.cancelledTrips</a></span>
            </h3>
        }
    </div>

    <div id="myTrips_main_wrap" class="container" style="margin-top: 0px;">
        <div id="CurrentTrips" class="selected">
            @foreach (ReservationForUser res in Model.reservations.Where(r => r.BookingStatus == (int)BookingStatus.CheckedIn || r.BookingStatus == (int)BookingStatus.FinalizedBooking || r.BookingStatus == (int)BookingStatus.ReceivedBooking).ToList())
            {
                @Trip(res, true);
            }
        </div>
        <div id="PastTrips" class="hidden">
            @foreach (ReservationForUser res in Model.reservations.Where(r => r.BookingStatus == (int)BookingStatus.CheckedOut || r.BookingStatus == (int)BookingStatus.DamageInvestigation || r.BookingStatus == (int)BookingStatus.Completed).ToList())
            {
                @Trip(res, false);
            }
        </div>
        <div id="CancelledTrips" class="hidden">
            @foreach (ReservationForUser res in Model.reservations.Where(r => r.BookingStatus == (int)BookingStatus.Cancelled).ToList())
            {
                @Trip(res, false);
            }
        </div>
    </div>

</section>

src/OTP/ExtranetApp/Views/Guest/OnSiteServices.cshtml
@using ExtranetApp.Resources.Views;

@{
    ViewBag.Title = Guest.OnSiteServices_Title;
}

@Html.ActionLink(Guest.OnSiteServices_Link_Back, "Index", "Home")